name: Deploy
on:
  push:
    branches:
      - customize-for-oauth-proxy # TODO: change to master
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_REGISTRY: ${{ secrets.REGISTRY_NAME_DEV }}.azurecr.io/tribia
      DOCKER_IMAGE: unleash
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME_DEV }}
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME_DEV }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME_DEV }}
          password: ${{ secrets.REGISTRY_PASSWORD_DEV }}
      - name: Build and publish docker image
        run: |
          docker build -t ${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE} .
          docker push ${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE}