# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_REGISTRY: ${{ secrets.REGISTRY_NAME_DEV }}.azurecr.io/tribia
      DOCKER_IMAGE: unleash
      DOCKER_IMAGE_TAG: 3.2.2
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME_DEV }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    # Docker login
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME_DEV }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME_DEV }}
        password: ${{ secrets.REGISTRY_PASSWORD_DEV }}

    # Build and publish docker image
    - name: Build and publish docker image
      run: |
        docker build -t ${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} .
        docker tag ${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG} latest
        docker push ${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE}
